version: '3'

services:
  visualizer:
    image: dockersamples/visualizer:stable
    container_name: swarm-visualizer
    ports:
      - "8091:8080"  # Change to 8091
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints:
          - node.role == manager
