services:
  python_service:
    build:
      context: .
      dockerfile: dockerfile.python
      args:
        - BASE_IMAGE=python:3.9
        - APP_VERSION=2.0
    environment:
      - DEBUG=true
    image: kamunge2004/python_web:2.1

  node_service:
    build:
      context: .
      dockerfile: dockerfile.node
      args:
        - BASE_IMAGE=node:21
        - APP_NAME=my-nodejs-app
    image: kamunge2004/node_web:2.1